/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { healthCheck } from '../fn/health-resource/health-check';
import { HealthCheck$Params } from '../fn/health-resource/health-check';

@Injectable({ providedIn: 'root' })
export class HealthResourceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `healthCheck()` */
  static readonly HealthCheckPath = '/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthCheck()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheck$Response(params?: HealthCheck$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return healthCheck(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthCheck$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheck(params?: HealthCheck$Params, context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.healthCheck$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

}
