/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskDto {
  assigneeId?: number;
  createdDate?: string;
  description?: string;
  dueDate: string | undefined | null;
  id?: number;
  lastModifiedDate?: string;
  status: 'TO_DO' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  title: string;
}
