/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  createdDate?: string;
  email: string;
  enabled: boolean;
  fullName: string;
  id: number;
  lastModifiedDate?: string;
  locked: boolean;
  roles: Array<string>;
}
