/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageTaskDto } from '../../models/page-task-dto';

export interface GetAllTasks$Params {

/**
 * Filter by title (optional)
 */
  title?: string;

/**
 * Filter by status (optional)
 */
  status?: 'TO_DO' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';

/**
 * Filter by assignee id (optional)
 */
  assigneeId?: number;

/**
 * Pagination parameters
 */
  pageable: Pageable;
}

export function getAllTasks(http: HttpClient, rootUrl: string, params: GetAllTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<PageTaskDto>> {
  const rb = new RequestBuilder(rootUrl, getAllTasks.PATH, 'get');
  if (params) {
    rb.query('title', params.title, {});
    rb.query('status', params.status, {});
    rb.query('assigneeId', params.assigneeId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageTaskDto>;
    })
  );
}

getAllTasks.PATH = '/tasks';
