spring:
    # DATA SOURCE CONFIGURATION
    datasource:
        username: devuser
        password: devpassword
        url: jdbc:postgresql://postgres-db:5432/devdb
        driver-class-name: org.postgresql.Driver

    # JPA CONFIGURATION
    jpa:
      hibernate:
            ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

    # FLYWAY CONFIGURATION
    flyway:
      locations: classpath:db/migration
      enabled: true