spring:
    # DATA SOURCE CONFIGURATION
    datasource:
        username: devuser
        password: devpassword
        url: jdbc:postgresql://localhost:5432/devdb
        driver-class-name: org.postgresql.Driver

    # JPA CONFIGURATION
    jpa:
      hibernate:
            ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 57ced04f05d112c683c2f5181f25ff89c782e595f5ec75ea760b84158257e47446a6fbb4ac7e60ab8751a02c42997f7bc159
      expiration: 86400000