server:
  port: 8080
  servlet:
    context-path: /api/
spring:
  profiles:
    active: dev
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  default-produces-media-type: application/json

