spring:
    # DATA SOURCE CONFIGURATION
    datasource:
        username: devuser
        password: devpassword
        url: jdbc:postgresql://localhost:5432/devdb
        driver-class-name: org.postgresql.Driver

    # JPA CONFIGURATION
    jpa:
      hibernate:
            ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

    # FLYWAY CONFIGURATION
    flyway:
      locations: classpath:db/migration
      enabled: true

application:
  security:
    jwt:
      secret-key: 4bde5458c449b71665b66214b1e7dfad8ada3f60895d23e1453b415fe4a5e46b
      expiration: 86400000